package es.jafs.jaiberdroid;

import java.lang.reflect.ParameterizedType;
import java.util.List;

import android.util.Log;
import es.jafs.jaiberdroid.Query.Type;

/**
 * Generic query. All the new querys must be inheritate from this.
 * @author  Jose Antonio Fuentes Santiago
 * @version 0.5
 * @param <T> Class of entity.
 */
public class GenericQuery<T> {
	/** Instance of Query Manager. */
	private static QueryManager queryManager;
	/** Instance of Entity Manager. */
	private static EntityManager entityManager;
	/** Entity of query. */
	private Entity entity;


	/**
	 * Default constructor of the class. 
	 */
	@SuppressWarnings("unchecked")
	public GenericQuery() {
		try {
			final Class<T> type = (Class<T>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[0];
			entity = JaiberdroidInstance.getInstance().getEntityManager().getEntity(type);

			if (null == queryManager) {
				queryManager = JaiberdroidInstance.getInstance().getQueryManager();
			}
			if (null == entityManager) {
				entityManager = JaiberdroidInstance.getInstance().getEntityManager();
			}
		} catch (final IllegalAccessException e) {
			Log.e(JaiberdroidInstance.LOG_TAG, e.getMessage());
		}
	}


	/**
	 * Get all elements of the table.
	 * @return A list of results generated by the query.
	 * @throws JaiberdroidException 
	 */
	@SuppressWarnings("unchecked")
	public List<T> getAll() throws JaiberdroidException {
		return (List<T>) queryManager.executeQueryEntity(new Query(Type.SELECT, entity.getReferenced()));
	}


	/**
	 * Find a object with its PK.
	 * @param  id  Id of the object to find.
	 * @return Object finded or null is not exists.
	 * @throws JaiberdroidException 
	 */
	@SuppressWarnings("unchecked")
	public T findByPk(final int id) throws JaiberdroidException {
		T current = null;

		final Query query = new Query(Type.SELECT, entity.getReferenced());
		query.addArg(id);
		query.setCondition(JaiberdroidSql._ID + " = ?");

		final List<T> resul = (List<T>) queryManager.executeQueryEntity(query);
		if (null != resul && !resul.isEmpty()) {
			current = resul.get(0);
		}

		return current;
	}


	/**
	 * Insert the received object.
	 * @param  object  Object to insert.
	 * @return True if the object was inserted.
	 * @throws JaiberdroidException 
	 */
	public boolean insert(final T object) throws JaiberdroidException {
		return (-1L != queryManager.executeUpdate(Query.createInsert(object)));
	}


	/**
	 * Update the received object.
	 * @param  object  Object to update.
	 * @return Number of rows affected.
	 * @throws JaiberdroidException 
	 */
	public long update(final T object) throws JaiberdroidException {
		return queryManager.executeUpdate(Query.createUpdate(object));
	}


	/**
	 * Delete an object with its id.
	 * @param  id  Id of the object to delete.
	 * @return Number of rows affected.
	 * @throws JaiberdroidException 
	 */
	public long remove(final int id) throws JaiberdroidException {
		return queryManager.executeUpdate(Query.createDelete(entity.getReferenced(), id));
	}


	/**
	 * Delete all objects in table.
	 * @return Number of rows affected.
	 * @throws JaiberdroidException 
	 */
	public long removeAll() throws JaiberdroidException {
		return queryManager.executeUpdate(Query.createDelete(entity.getReferenced(), -1));
	}


	/**
	 * Gets a boolean value that is true if object with id received exists.
	 * @param  id  Id of the object to find.
	 * @return Boolean value that is true if object with id received exists.
	 * @throws JaiberdroidException 
	 */
	public boolean exists(final int id) throws JaiberdroidException {
		return (null != findByPk(id));
	}


	/**
	 * Gets the rows number.
	 * @return Long with rows number.
	 * @throws JaiberdroidException 
	 */
	public long count() throws JaiberdroidException {
		return queryManager.executeCountQuery(entity);
	}
}
